// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goreact/ent/albumimage"
	"goreact/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlbumImageQuery is the builder for querying AlbumImage entities.
type AlbumImageQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.AlbumImage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AlbumImageQuery builder.
func (aiq *AlbumImageQuery) Where(ps ...predicate.AlbumImage) *AlbumImageQuery {
	aiq.predicates = append(aiq.predicates, ps...)
	return aiq
}

// Limit adds a limit step to the query.
func (aiq *AlbumImageQuery) Limit(limit int) *AlbumImageQuery {
	aiq.limit = &limit
	return aiq
}

// Offset adds an offset step to the query.
func (aiq *AlbumImageQuery) Offset(offset int) *AlbumImageQuery {
	aiq.offset = &offset
	return aiq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aiq *AlbumImageQuery) Unique(unique bool) *AlbumImageQuery {
	aiq.unique = &unique
	return aiq
}

// Order adds an order step to the query.
func (aiq *AlbumImageQuery) Order(o ...OrderFunc) *AlbumImageQuery {
	aiq.order = append(aiq.order, o...)
	return aiq
}

// First returns the first AlbumImage entity from the query.
// Returns a *NotFoundError when no AlbumImage was found.
func (aiq *AlbumImageQuery) First(ctx context.Context) (*AlbumImage, error) {
	nodes, err := aiq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{albumimage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aiq *AlbumImageQuery) FirstX(ctx context.Context) *AlbumImage {
	node, err := aiq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AlbumImage ID from the query.
// Returns a *NotFoundError when no AlbumImage ID was found.
func (aiq *AlbumImageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{albumimage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aiq *AlbumImageQuery) FirstIDX(ctx context.Context) int {
	id, err := aiq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AlbumImage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one AlbumImage entity is not found.
// Returns a *NotFoundError when no AlbumImage entities are found.
func (aiq *AlbumImageQuery) Only(ctx context.Context) (*AlbumImage, error) {
	nodes, err := aiq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{albumimage.Label}
	default:
		return nil, &NotSingularError{albumimage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aiq *AlbumImageQuery) OnlyX(ctx context.Context) *AlbumImage {
	node, err := aiq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AlbumImage ID in the query.
// Returns a *NotSingularError when exactly one AlbumImage ID is not found.
// Returns a *NotFoundError when no entities are found.
func (aiq *AlbumImageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = aiq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = &NotSingularError{albumimage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aiq *AlbumImageQuery) OnlyIDX(ctx context.Context) int {
	id, err := aiq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AlbumImages.
func (aiq *AlbumImageQuery) All(ctx context.Context) ([]*AlbumImage, error) {
	if err := aiq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return aiq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (aiq *AlbumImageQuery) AllX(ctx context.Context) []*AlbumImage {
	nodes, err := aiq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AlbumImage IDs.
func (aiq *AlbumImageQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := aiq.Select(albumimage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aiq *AlbumImageQuery) IDsX(ctx context.Context) []int {
	ids, err := aiq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aiq *AlbumImageQuery) Count(ctx context.Context) (int, error) {
	if err := aiq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return aiq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (aiq *AlbumImageQuery) CountX(ctx context.Context) int {
	count, err := aiq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aiq *AlbumImageQuery) Exist(ctx context.Context) (bool, error) {
	if err := aiq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return aiq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (aiq *AlbumImageQuery) ExistX(ctx context.Context) bool {
	exist, err := aiq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AlbumImageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aiq *AlbumImageQuery) Clone() *AlbumImageQuery {
	if aiq == nil {
		return nil
	}
	return &AlbumImageQuery{
		config:     aiq.config,
		limit:      aiq.limit,
		offset:     aiq.offset,
		order:      append([]OrderFunc{}, aiq.order...),
		predicates: append([]predicate.AlbumImage{}, aiq.predicates...),
		// clone intermediate query.
		sql:  aiq.sql.Clone(),
		path: aiq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Image []byte `json:"image,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AlbumImage.Query().
//		GroupBy(albumimage.FieldImage).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (aiq *AlbumImageQuery) GroupBy(field string, fields ...string) *AlbumImageGroupBy {
	group := &AlbumImageGroupBy{config: aiq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := aiq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return aiq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Image []byte `json:"image,omitempty"`
//	}
//
//	client.AlbumImage.Query().
//		Select(albumimage.FieldImage).
//		Scan(ctx, &v)
//
func (aiq *AlbumImageQuery) Select(field string, fields ...string) *AlbumImageSelect {
	aiq.fields = append([]string{field}, fields...)
	return &AlbumImageSelect{AlbumImageQuery: aiq}
}

func (aiq *AlbumImageQuery) prepareQuery(ctx context.Context) error {
	for _, f := range aiq.fields {
		if !albumimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aiq.path != nil {
		prev, err := aiq.path(ctx)
		if err != nil {
			return err
		}
		aiq.sql = prev
	}
	return nil
}

func (aiq *AlbumImageQuery) sqlAll(ctx context.Context) ([]*AlbumImage, error) {
	var (
		nodes = []*AlbumImage{}
		_spec = aiq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &AlbumImage{config: aiq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, aiq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (aiq *AlbumImageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aiq.querySpec()
	return sqlgraph.CountNodes(ctx, aiq.driver, _spec)
}

func (aiq *AlbumImageQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := aiq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (aiq *AlbumImageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   albumimage.Table,
			Columns: albumimage.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: albumimage.FieldID,
			},
		},
		From:   aiq.sql,
		Unique: true,
	}
	if unique := aiq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := aiq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, albumimage.FieldID)
		for i := range fields {
			if fields[i] != albumimage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := aiq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aiq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aiq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aiq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aiq *AlbumImageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aiq.driver.Dialect())
	t1 := builder.Table(albumimage.Table)
	columns := aiq.fields
	if len(columns) == 0 {
		columns = albumimage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aiq.sql != nil {
		selector = aiq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range aiq.predicates {
		p(selector)
	}
	for _, p := range aiq.order {
		p(selector)
	}
	if offset := aiq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aiq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AlbumImageGroupBy is the group-by builder for AlbumImage entities.
type AlbumImageGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (aigb *AlbumImageGroupBy) Aggregate(fns ...AggregateFunc) *AlbumImageGroupBy {
	aigb.fns = append(aigb.fns, fns...)
	return aigb
}

// Scan applies the group-by query and scans the result into the given value.
func (aigb *AlbumImageGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := aigb.path(ctx)
	if err != nil {
		return err
	}
	aigb.sql = query
	return aigb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := aigb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: AlbumImageGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) StringsX(ctx context.Context) []string {
	v, err := aigb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = aigb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) StringX(ctx context.Context) string {
	v, err := aigb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: AlbumImageGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) IntsX(ctx context.Context) []int {
	v, err := aigb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = aigb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) IntX(ctx context.Context) int {
	v, err := aigb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: AlbumImageGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := aigb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = aigb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) Float64X(ctx context.Context) float64 {
	v, err := aigb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(aigb.fields) > 1 {
		return nil, errors.New("ent: AlbumImageGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := aigb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := aigb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (aigb *AlbumImageGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = aigb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (aigb *AlbumImageGroupBy) BoolX(ctx context.Context) bool {
	v, err := aigb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (aigb *AlbumImageGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range aigb.fields {
		if !albumimage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := aigb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := aigb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (aigb *AlbumImageGroupBy) sqlQuery() *sql.Selector {
	selector := aigb.sql.Select()
	aggregation := make([]string, 0, len(aigb.fns))
	for _, fn := range aigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(aigb.fields)+len(aigb.fns))
		for _, f := range aigb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(aigb.fields...)...)
}

// AlbumImageSelect is the builder for selecting fields of AlbumImage entities.
type AlbumImageSelect struct {
	*AlbumImageQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ais *AlbumImageSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ais.prepareQuery(ctx); err != nil {
		return err
	}
	ais.sql = ais.AlbumImageQuery.sqlQuery(ctx)
	return ais.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ais *AlbumImageSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ais.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: AlbumImageSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ais *AlbumImageSelect) StringsX(ctx context.Context) []string {
	v, err := ais.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ais.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ais *AlbumImageSelect) StringX(ctx context.Context) string {
	v, err := ais.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: AlbumImageSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ais *AlbumImageSelect) IntsX(ctx context.Context) []int {
	v, err := ais.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ais.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ais *AlbumImageSelect) IntX(ctx context.Context) int {
	v, err := ais.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: AlbumImageSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ais *AlbumImageSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ais.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ais.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ais *AlbumImageSelect) Float64X(ctx context.Context) float64 {
	v, err := ais.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ais.fields) > 1 {
		return nil, errors.New("ent: AlbumImageSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ais.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ais *AlbumImageSelect) BoolsX(ctx context.Context) []bool {
	v, err := ais.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ais *AlbumImageSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ais.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{albumimage.Label}
	default:
		err = fmt.Errorf("ent: AlbumImageSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ais *AlbumImageSelect) BoolX(ctx context.Context) bool {
	v, err := ais.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ais *AlbumImageSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ais.sql.Query()
	if err := ais.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
