// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orkester/ent/albumimage"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AlbumImageCreate is the builder for creating a AlbumImage entity.
type AlbumImageCreate struct {
	config
	mutation *AlbumImageMutation
	hooks    []Hook
}

// SetImage sets the "image" field.
func (aic *AlbumImageCreate) SetImage(b []byte) *AlbumImageCreate {
	aic.mutation.SetImage(b)
	return aic
}

// SetImageMimeType sets the "image_mime_type" field.
func (aic *AlbumImageCreate) SetImageMimeType(s string) *AlbumImageCreate {
	aic.mutation.SetImageMimeType(s)
	return aic
}

// Mutation returns the AlbumImageMutation object of the builder.
func (aic *AlbumImageCreate) Mutation() *AlbumImageMutation {
	return aic.mutation
}

// Save creates the AlbumImage in the database.
func (aic *AlbumImageCreate) Save(ctx context.Context) (*AlbumImage, error) {
	var (
		err  error
		node *AlbumImage
	)
	if len(aic.hooks) == 0 {
		if err = aic.check(); err != nil {
			return nil, err
		}
		node, err = aic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AlbumImageMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = aic.check(); err != nil {
				return nil, err
			}
			aic.mutation = mutation
			if node, err = aic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(aic.hooks) - 1; i >= 0; i-- {
			if aic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aic.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, aic.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AlbumImage)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AlbumImageMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (aic *AlbumImageCreate) SaveX(ctx context.Context) *AlbumImage {
	v, err := aic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aic *AlbumImageCreate) Exec(ctx context.Context) error {
	_, err := aic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aic *AlbumImageCreate) ExecX(ctx context.Context) {
	if err := aic.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aic *AlbumImageCreate) check() error {
	if _, ok := aic.mutation.Image(); !ok {
		return &ValidationError{Name: "image", err: errors.New(`ent: missing required field "AlbumImage.image"`)}
	}
	if _, ok := aic.mutation.ImageMimeType(); !ok {
		return &ValidationError{Name: "image_mime_type", err: errors.New(`ent: missing required field "AlbumImage.image_mime_type"`)}
	}
	return nil
}

func (aic *AlbumImageCreate) sqlSave(ctx context.Context) (*AlbumImage, error) {
	_node, _spec := aic.createSpec()
	if err := sqlgraph.CreateNode(ctx, aic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (aic *AlbumImageCreate) createSpec() (*AlbumImage, *sqlgraph.CreateSpec) {
	var (
		_node = &AlbumImage{config: aic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: albumimage.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: albumimage.FieldID,
			},
		}
	)
	if value, ok := aic.mutation.Image(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Value:  value,
			Column: albumimage.FieldImage,
		})
		_node.Image = value
	}
	if value, ok := aic.mutation.ImageMimeType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: albumimage.FieldImageMimeType,
		})
		_node.ImageMimeType = value
	}
	return _node, _spec
}

// AlbumImageCreateBulk is the builder for creating many AlbumImage entities in bulk.
type AlbumImageCreateBulk struct {
	config
	builders []*AlbumImageCreate
}

// Save creates the AlbumImage entities in the database.
func (aicb *AlbumImageCreateBulk) Save(ctx context.Context) ([]*AlbumImage, error) {
	specs := make([]*sqlgraph.CreateSpec, len(aicb.builders))
	nodes := make([]*AlbumImage, len(aicb.builders))
	mutators := make([]Mutator, len(aicb.builders))
	for i := range aicb.builders {
		func(i int, root context.Context) {
			builder := aicb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlbumImageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aicb *AlbumImageCreateBulk) SaveX(ctx context.Context) []*AlbumImage {
	v, err := aicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aicb *AlbumImageCreateBulk) Exec(ctx context.Context) error {
	_, err := aicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aicb *AlbumImageCreateBulk) ExecX(ctx context.Context) {
	if err := aicb.Exec(ctx); err != nil {
		panic(err)
	}
}
