// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"orkester/ent/likedtrack"
	"orkester/ent/track"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// LikedTrack is the model entity for the LikedTrack schema.
type LikedTrack struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DateAdded holds the value of the "date_added" field.
	DateAdded time.Time `json:"date_added,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LikedTrackQuery when eager-loading is set.
	Edges        LikedTrackEdges `json:"edges"`
	track_liked  *int
	selectValues sql.SelectValues
}

// LikedTrackEdges holds the relations/edges for other nodes in the graph.
type LikedTrackEdges struct {
	// Track holds the value of the track edge.
	Track *Track `json:"track,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// TrackOrErr returns the Track value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LikedTrackEdges) TrackOrErr() (*Track, error) {
	if e.Track != nil {
		return e.Track, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: track.Label}
	}
	return nil, &NotLoadedError{edge: "track"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LikedTrack) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case likedtrack.FieldID:
			values[i] = new(sql.NullInt64)
		case likedtrack.FieldDateAdded:
			values[i] = new(sql.NullTime)
		case likedtrack.ForeignKeys[0]: // track_liked
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LikedTrack fields.
func (lt *LikedTrack) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case likedtrack.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			lt.ID = int(value.Int64)
		case likedtrack.FieldDateAdded:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date_added", values[i])
			} else if value.Valid {
				lt.DateAdded = value.Time
			}
		case likedtrack.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field track_liked", value)
			} else if value.Valid {
				lt.track_liked = new(int)
				*lt.track_liked = int(value.Int64)
			}
		default:
			lt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LikedTrack.
// This includes values selected through modifiers, order, etc.
func (lt *LikedTrack) Value(name string) (ent.Value, error) {
	return lt.selectValues.Get(name)
}

// QueryTrack queries the "track" edge of the LikedTrack entity.
func (lt *LikedTrack) QueryTrack() *TrackQuery {
	return NewLikedTrackClient(lt.config).QueryTrack(lt)
}

// Update returns a builder for updating this LikedTrack.
// Note that you need to call LikedTrack.Unwrap() before calling this method if this LikedTrack
// was returned from a transaction, and the transaction was committed or rolled back.
func (lt *LikedTrack) Update() *LikedTrackUpdateOne {
	return NewLikedTrackClient(lt.config).UpdateOne(lt)
}

// Unwrap unwraps the LikedTrack entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (lt *LikedTrack) Unwrap() *LikedTrack {
	_tx, ok := lt.config.driver.(*txDriver)
	if !ok {
		panic("ent: LikedTrack is not a transactional entity")
	}
	lt.config.driver = _tx.drv
	return lt
}

// String implements the fmt.Stringer.
func (lt *LikedTrack) String() string {
	var builder strings.Builder
	builder.WriteString("LikedTrack(")
	builder.WriteString(fmt.Sprintf("id=%v, ", lt.ID))
	builder.WriteString("date_added=")
	builder.WriteString(lt.DateAdded.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LikedTracks is a parsable slice of LikedTrack.
type LikedTracks []*LikedTrack
