// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goreact/ent/likedtrack"
	"goreact/ent/predicate"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikedTrackQuery is the builder for querying LikedTrack entities.
type LikedTrackQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LikedTrack
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LikedTrackQuery builder.
func (ltq *LikedTrackQuery) Where(ps ...predicate.LikedTrack) *LikedTrackQuery {
	ltq.predicates = append(ltq.predicates, ps...)
	return ltq
}

// Limit adds a limit step to the query.
func (ltq *LikedTrackQuery) Limit(limit int) *LikedTrackQuery {
	ltq.limit = &limit
	return ltq
}

// Offset adds an offset step to the query.
func (ltq *LikedTrackQuery) Offset(offset int) *LikedTrackQuery {
	ltq.offset = &offset
	return ltq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ltq *LikedTrackQuery) Unique(unique bool) *LikedTrackQuery {
	ltq.unique = &unique
	return ltq
}

// Order adds an order step to the query.
func (ltq *LikedTrackQuery) Order(o ...OrderFunc) *LikedTrackQuery {
	ltq.order = append(ltq.order, o...)
	return ltq
}

// First returns the first LikedTrack entity from the query.
// Returns a *NotFoundError when no LikedTrack was found.
func (ltq *LikedTrackQuery) First(ctx context.Context) (*LikedTrack, error) {
	nodes, err := ltq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{likedtrack.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ltq *LikedTrackQuery) FirstX(ctx context.Context) *LikedTrack {
	node, err := ltq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LikedTrack ID from the query.
// Returns a *NotFoundError when no LikedTrack ID was found.
func (ltq *LikedTrackQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{likedtrack.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ltq *LikedTrackQuery) FirstIDX(ctx context.Context) int {
	id, err := ltq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LikedTrack entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LikedTrack entity is not found.
// Returns a *NotFoundError when no LikedTrack entities are found.
func (ltq *LikedTrackQuery) Only(ctx context.Context) (*LikedTrack, error) {
	nodes, err := ltq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{likedtrack.Label}
	default:
		return nil, &NotSingularError{likedtrack.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ltq *LikedTrackQuery) OnlyX(ctx context.Context) *LikedTrack {
	node, err := ltq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LikedTrack ID in the query.
// Returns a *NotSingularError when exactly one LikedTrack ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ltq *LikedTrackQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = &NotSingularError{likedtrack.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ltq *LikedTrackQuery) OnlyIDX(ctx context.Context) int {
	id, err := ltq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LikedTracks.
func (ltq *LikedTrackQuery) All(ctx context.Context) ([]*LikedTrack, error) {
	if err := ltq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ltq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ltq *LikedTrackQuery) AllX(ctx context.Context) []*LikedTrack {
	nodes, err := ltq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LikedTrack IDs.
func (ltq *LikedTrackQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ltq.Select(likedtrack.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ltq *LikedTrackQuery) IDsX(ctx context.Context) []int {
	ids, err := ltq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ltq *LikedTrackQuery) Count(ctx context.Context) (int, error) {
	if err := ltq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ltq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ltq *LikedTrackQuery) CountX(ctx context.Context) int {
	count, err := ltq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ltq *LikedTrackQuery) Exist(ctx context.Context) (bool, error) {
	if err := ltq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ltq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ltq *LikedTrackQuery) ExistX(ctx context.Context) bool {
	exist, err := ltq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LikedTrackQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ltq *LikedTrackQuery) Clone() *LikedTrackQuery {
	if ltq == nil {
		return nil
	}
	return &LikedTrackQuery{
		config:     ltq.config,
		limit:      ltq.limit,
		offset:     ltq.offset,
		order:      append([]OrderFunc{}, ltq.order...),
		predicates: append([]predicate.LikedTrack{}, ltq.predicates...),
		// clone intermediate query.
		sql:  ltq.sql.Clone(),
		path: ltq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DateAdded time.Time `json:"date_added,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LikedTrack.Query().
//		GroupBy(likedtrack.FieldDateAdded).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ltq *LikedTrackQuery) GroupBy(field string, fields ...string) *LikedTrackGroupBy {
	group := &LikedTrackGroupBy{config: ltq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ltq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DateAdded time.Time `json:"date_added,omitempty"`
//	}
//
//	client.LikedTrack.Query().
//		Select(likedtrack.FieldDateAdded).
//		Scan(ctx, &v)
//
func (ltq *LikedTrackQuery) Select(field string, fields ...string) *LikedTrackSelect {
	ltq.fields = append([]string{field}, fields...)
	return &LikedTrackSelect{LikedTrackQuery: ltq}
}

func (ltq *LikedTrackQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ltq.fields {
		if !likedtrack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ltq.path != nil {
		prev, err := ltq.path(ctx)
		if err != nil {
			return err
		}
		ltq.sql = prev
	}
	return nil
}

func (ltq *LikedTrackQuery) sqlAll(ctx context.Context) ([]*LikedTrack, error) {
	var (
		nodes = []*LikedTrack{}
		_spec = ltq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LikedTrack{config: ltq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ltq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ltq *LikedTrackQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ltq.querySpec()
	return sqlgraph.CountNodes(ctx, ltq.driver, _spec)
}

func (ltq *LikedTrackQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ltq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ltq *LikedTrackQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   likedtrack.Table,
			Columns: likedtrack.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: likedtrack.FieldID,
			},
		},
		From:   ltq.sql,
		Unique: true,
	}
	if unique := ltq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ltq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, likedtrack.FieldID)
		for i := range fields {
			if fields[i] != likedtrack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ltq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ltq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ltq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ltq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ltq *LikedTrackQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ltq.driver.Dialect())
	t1 := builder.Table(likedtrack.Table)
	columns := ltq.fields
	if len(columns) == 0 {
		columns = likedtrack.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ltq.sql != nil {
		selector = ltq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ltq.predicates {
		p(selector)
	}
	for _, p := range ltq.order {
		p(selector)
	}
	if offset := ltq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ltq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LikedTrackGroupBy is the group-by builder for LikedTrack entities.
type LikedTrackGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ltgb *LikedTrackGroupBy) Aggregate(fns ...AggregateFunc) *LikedTrackGroupBy {
	ltgb.fns = append(ltgb.fns, fns...)
	return ltgb
}

// Scan applies the group-by query and scans the result into the given value.
func (ltgb *LikedTrackGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ltgb.path(ctx)
	if err != nil {
		return err
	}
	ltgb.sql = query
	return ltgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ltgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ltgb.fields) > 1 {
		return nil, errors.New("ent: LikedTrackGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ltgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) StringsX(ctx context.Context) []string {
	v, err := ltgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ltgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) StringX(ctx context.Context) string {
	v, err := ltgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ltgb.fields) > 1 {
		return nil, errors.New("ent: LikedTrackGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ltgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) IntsX(ctx context.Context) []int {
	v, err := ltgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ltgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) IntX(ctx context.Context) int {
	v, err := ltgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ltgb.fields) > 1 {
		return nil, errors.New("ent: LikedTrackGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ltgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ltgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ltgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ltgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ltgb.fields) > 1 {
		return nil, errors.New("ent: LikedTrackGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ltgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ltgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ltgb *LikedTrackGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ltgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ltgb *LikedTrackGroupBy) BoolX(ctx context.Context) bool {
	v, err := ltgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ltgb *LikedTrackGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ltgb.fields {
		if !likedtrack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ltgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ltgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ltgb *LikedTrackGroupBy) sqlQuery() *sql.Selector {
	selector := ltgb.sql.Select()
	aggregation := make([]string, 0, len(ltgb.fns))
	for _, fn := range ltgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ltgb.fields)+len(ltgb.fns))
		for _, f := range ltgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ltgb.fields...)...)
}

// LikedTrackSelect is the builder for selecting fields of LikedTrack entities.
type LikedTrackSelect struct {
	*LikedTrackQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lts *LikedTrackSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lts.prepareQuery(ctx); err != nil {
		return err
	}
	lts.sql = lts.LikedTrackQuery.sqlQuery(ctx)
	return lts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lts *LikedTrackSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lts.fields) > 1 {
		return nil, errors.New("ent: LikedTrackSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lts *LikedTrackSelect) StringsX(ctx context.Context) []string {
	v, err := lts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lts *LikedTrackSelect) StringX(ctx context.Context) string {
	v, err := lts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lts.fields) > 1 {
		return nil, errors.New("ent: LikedTrackSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lts *LikedTrackSelect) IntsX(ctx context.Context) []int {
	v, err := lts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lts *LikedTrackSelect) IntX(ctx context.Context) int {
	v, err := lts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lts.fields) > 1 {
		return nil, errors.New("ent: LikedTrackSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lts *LikedTrackSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lts *LikedTrackSelect) Float64X(ctx context.Context) float64 {
	v, err := lts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lts.fields) > 1 {
		return nil, errors.New("ent: LikedTrackSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lts *LikedTrackSelect) BoolsX(ctx context.Context) []bool {
	v, err := lts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lts *LikedTrackSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = fmt.Errorf("ent: LikedTrackSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lts *LikedTrackSelect) BoolX(ctx context.Context) bool {
	v, err := lts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lts *LikedTrackSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lts.sql.Query()
	if err := lts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
