// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"orkester/ent/likedtrack"
	"orkester/ent/track"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikedTrackCreate is the builder for creating a LikedTrack entity.
type LikedTrackCreate struct {
	config
	mutation *LikedTrackMutation
	hooks    []Hook
}

// SetDateAdded sets the "date_added" field.
func (ltc *LikedTrackCreate) SetDateAdded(t time.Time) *LikedTrackCreate {
	ltc.mutation.SetDateAdded(t)
	return ltc
}

// SetNillableDateAdded sets the "date_added" field if the given value is not nil.
func (ltc *LikedTrackCreate) SetNillableDateAdded(t *time.Time) *LikedTrackCreate {
	if t != nil {
		ltc.SetDateAdded(*t)
	}
	return ltc
}

// SetTrackID sets the "track" edge to the Track entity by ID.
func (ltc *LikedTrackCreate) SetTrackID(id int) *LikedTrackCreate {
	ltc.mutation.SetTrackID(id)
	return ltc
}

// SetTrack sets the "track" edge to the Track entity.
func (ltc *LikedTrackCreate) SetTrack(t *Track) *LikedTrackCreate {
	return ltc.SetTrackID(t.ID)
}

// Mutation returns the LikedTrackMutation object of the builder.
func (ltc *LikedTrackCreate) Mutation() *LikedTrackMutation {
	return ltc.mutation
}

// Save creates the LikedTrack in the database.
func (ltc *LikedTrackCreate) Save(ctx context.Context) (*LikedTrack, error) {
	ltc.defaults()
	return withHooks(ctx, ltc.sqlSave, ltc.mutation, ltc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ltc *LikedTrackCreate) SaveX(ctx context.Context) *LikedTrack {
	v, err := ltc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltc *LikedTrackCreate) Exec(ctx context.Context) error {
	_, err := ltc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltc *LikedTrackCreate) ExecX(ctx context.Context) {
	if err := ltc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ltc *LikedTrackCreate) defaults() {
	if _, ok := ltc.mutation.DateAdded(); !ok {
		v := likedtrack.DefaultDateAdded()
		ltc.mutation.SetDateAdded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ltc *LikedTrackCreate) check() error {
	if _, ok := ltc.mutation.DateAdded(); !ok {
		return &ValidationError{Name: "date_added", err: errors.New(`ent: missing required field "LikedTrack.date_added"`)}
	}
	if _, ok := ltc.mutation.TrackID(); !ok {
		return &ValidationError{Name: "track", err: errors.New(`ent: missing required edge "LikedTrack.track"`)}
	}
	return nil
}

func (ltc *LikedTrackCreate) sqlSave(ctx context.Context) (*LikedTrack, error) {
	if err := ltc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ltc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ltc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ltc.mutation.id = &_node.ID
	ltc.mutation.done = true
	return _node, nil
}

func (ltc *LikedTrackCreate) createSpec() (*LikedTrack, *sqlgraph.CreateSpec) {
	var (
		_node = &LikedTrack{config: ltc.config}
		_spec = sqlgraph.NewCreateSpec(likedtrack.Table, sqlgraph.NewFieldSpec(likedtrack.FieldID, field.TypeInt))
	)
	if value, ok := ltc.mutation.DateAdded(); ok {
		_spec.SetField(likedtrack.FieldDateAdded, field.TypeTime, value)
		_node.DateAdded = value
	}
	if nodes := ltc.mutation.TrackIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   likedtrack.TrackTable,
			Columns: []string{likedtrack.TrackColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.track_liked = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LikedTrackCreateBulk is the builder for creating many LikedTrack entities in bulk.
type LikedTrackCreateBulk struct {
	config
	err      error
	builders []*LikedTrackCreate
}

// Save creates the LikedTrack entities in the database.
func (ltcb *LikedTrackCreateBulk) Save(ctx context.Context) ([]*LikedTrack, error) {
	if ltcb.err != nil {
		return nil, ltcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ltcb.builders))
	nodes := make([]*LikedTrack, len(ltcb.builders))
	mutators := make([]Mutator, len(ltcb.builders))
	for i := range ltcb.builders {
		func(i int, root context.Context) {
			builder := ltcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LikedTrackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ltcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ltcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ltcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ltcb *LikedTrackCreateBulk) SaveX(ctx context.Context) []*LikedTrack {
	v, err := ltcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ltcb *LikedTrackCreateBulk) Exec(ctx context.Context) error {
	_, err := ltcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ltcb *LikedTrackCreateBulk) ExecX(ctx context.Context) {
	if err := ltcb.Exec(ctx); err != nil {
		panic(err)
	}
}
