// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"orkester/ent/likedtrack"
	"orkester/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikedTrackDelete is the builder for deleting a LikedTrack entity.
type LikedTrackDelete struct {
	config
	hooks    []Hook
	mutation *LikedTrackMutation
}

// Where appends a list predicates to the LikedTrackDelete builder.
func (ltd *LikedTrackDelete) Where(ps ...predicate.LikedTrack) *LikedTrackDelete {
	ltd.mutation.Where(ps...)
	return ltd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ltd *LikedTrackDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ltd.sqlExec, ltd.mutation, ltd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ltd *LikedTrackDelete) ExecX(ctx context.Context) int {
	n, err := ltd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ltd *LikedTrackDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(likedtrack.Table, sqlgraph.NewFieldSpec(likedtrack.FieldID, field.TypeInt))
	if ps := ltd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ltd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ltd.mutation.done = true
	return affected, err
}

// LikedTrackDeleteOne is the builder for deleting a single LikedTrack entity.
type LikedTrackDeleteOne struct {
	ltd *LikedTrackDelete
}

// Where appends a list predicates to the LikedTrackDelete builder.
func (ltdo *LikedTrackDeleteOne) Where(ps ...predicate.LikedTrack) *LikedTrackDeleteOne {
	ltdo.ltd.mutation.Where(ps...)
	return ltdo
}

// Exec executes the deletion query.
func (ltdo *LikedTrackDeleteOne) Exec(ctx context.Context) error {
	n, err := ltdo.ltd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{likedtrack.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ltdo *LikedTrackDeleteOne) ExecX(ctx context.Context) {
	if err := ltdo.Exec(ctx); err != nil {
		panic(err)
	}
}
