// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"goreact/ent/likedtrack"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikedTrackCreate is the builder for creating a LikedTrack entity.
type LikedTrackCreate struct {
	config
	mutation *LikedTrackMutation
	hooks    []Hook
}

// SetDateAdded sets the "date_added" field.
func (ltc *LikedTrackCreate) SetDateAdded(t time.Time) *LikedTrackCreate {
	ltc.mutation.SetDateAdded(t)
	return ltc
}

// SetNillableDateAdded sets the "date_added" field if the given value is not nil.
func (ltc *LikedTrackCreate) SetNillableDateAdded(t *time.Time) *LikedTrackCreate {
	if t != nil {
		ltc.SetDateAdded(*t)
	}
	return ltc
}

// Mutation returns the LikedTrackMutation object of the builder.
func (ltc *LikedTrackCreate) Mutation() *LikedTrackMutation {
	return ltc.mutation
}

// Save creates the LikedTrack in the database.
func (ltc *LikedTrackCreate) Save(ctx context.Context) (*LikedTrack, error) {
	var (
		err  error
		node *LikedTrack
	)
	ltc.defaults()
	if len(ltc.hooks) == 0 {
		if err = ltc.check(); err != nil {
			return nil, err
		}
		node, err = ltc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*LikedTrackMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ltc.check(); err != nil {
				return nil, err
			}
			ltc.mutation = mutation
			if node, err = ltc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ltc.hooks) - 1; i >= 0; i-- {
			mut = ltc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ltc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ltc *LikedTrackCreate) SaveX(ctx context.Context) *LikedTrack {
	v, err := ltc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// defaults sets the default values of the builder before save.
func (ltc *LikedTrackCreate) defaults() {
	if _, ok := ltc.mutation.DateAdded(); !ok {
		v := likedtrack.DefaultDateAdded()
		ltc.mutation.SetDateAdded(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ltc *LikedTrackCreate) check() error {
	if _, ok := ltc.mutation.DateAdded(); !ok {
		return &ValidationError{Name: "date_added", err: errors.New("ent: missing required field \"date_added\"")}
	}
	return nil
}

func (ltc *LikedTrackCreate) sqlSave(ctx context.Context) (*LikedTrack, error) {
	_node, _spec := ltc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ltc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ltc *LikedTrackCreate) createSpec() (*LikedTrack, *sqlgraph.CreateSpec) {
	var (
		_node = &LikedTrack{config: ltc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: likedtrack.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: likedtrack.FieldID,
			},
		}
	)
	if value, ok := ltc.mutation.DateAdded(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: likedtrack.FieldDateAdded,
		})
		_node.DateAdded = value
	}
	return _node, _spec
}

// LikedTrackCreateBulk is the builder for creating many LikedTrack entities in bulk.
type LikedTrackCreateBulk struct {
	config
	builders []*LikedTrackCreate
}

// Save creates the LikedTrack entities in the database.
func (ltcb *LikedTrackCreateBulk) Save(ctx context.Context) ([]*LikedTrack, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ltcb.builders))
	nodes := make([]*LikedTrack, len(ltcb.builders))
	mutators := make([]Mutator, len(ltcb.builders))
	for i := range ltcb.builders {
		func(i int, root context.Context) {
			builder := ltcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LikedTrackMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ltcb.builders[i+1].mutation)
				} else {
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ltcb.driver, &sqlgraph.BatchCreateSpec{Nodes: specs}); err != nil {
						if cerr, ok := isSQLConstraintError(err); ok {
							err = cerr
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				id := specs[i].ID.Value.(int64)
				nodes[i].ID = int(id)
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ltcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ltcb *LikedTrackCreateBulk) SaveX(ctx context.Context) []*LikedTrack {
	v, err := ltcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}
