// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"orkester/ent/likedtrack"
	"orkester/ent/predicate"
	"orkester/ent/track"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikedTrackQuery is the builder for querying LikedTrack entities.
type LikedTrackQuery struct {
	config
	ctx        *QueryContext
	order      []likedtrack.OrderOption
	inters     []Interceptor
	predicates []predicate.LikedTrack
	withTrack  *TrackQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LikedTrackQuery builder.
func (ltq *LikedTrackQuery) Where(ps ...predicate.LikedTrack) *LikedTrackQuery {
	ltq.predicates = append(ltq.predicates, ps...)
	return ltq
}

// Limit the number of records to be returned by this query.
func (ltq *LikedTrackQuery) Limit(limit int) *LikedTrackQuery {
	ltq.ctx.Limit = &limit
	return ltq
}

// Offset to start from.
func (ltq *LikedTrackQuery) Offset(offset int) *LikedTrackQuery {
	ltq.ctx.Offset = &offset
	return ltq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ltq *LikedTrackQuery) Unique(unique bool) *LikedTrackQuery {
	ltq.ctx.Unique = &unique
	return ltq
}

// Order specifies how the records should be ordered.
func (ltq *LikedTrackQuery) Order(o ...likedtrack.OrderOption) *LikedTrackQuery {
	ltq.order = append(ltq.order, o...)
	return ltq
}

// QueryTrack chains the current query on the "track" edge.
func (ltq *LikedTrackQuery) QueryTrack() *TrackQuery {
	query := (&TrackClient{config: ltq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ltq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ltq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(likedtrack.Table, likedtrack.FieldID, selector),
			sqlgraph.To(track.Table, track.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, likedtrack.TrackTable, likedtrack.TrackColumn),
		)
		fromU = sqlgraph.SetNeighbors(ltq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first LikedTrack entity from the query.
// Returns a *NotFoundError when no LikedTrack was found.
func (ltq *LikedTrackQuery) First(ctx context.Context) (*LikedTrack, error) {
	nodes, err := ltq.Limit(1).All(setContextOp(ctx, ltq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{likedtrack.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ltq *LikedTrackQuery) FirstX(ctx context.Context) *LikedTrack {
	node, err := ltq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LikedTrack ID from the query.
// Returns a *NotFoundError when no LikedTrack ID was found.
func (ltq *LikedTrackQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(1).IDs(setContextOp(ctx, ltq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{likedtrack.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ltq *LikedTrackQuery) FirstIDX(ctx context.Context) int {
	id, err := ltq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LikedTrack entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one LikedTrack entity is found.
// Returns a *NotFoundError when no LikedTrack entities are found.
func (ltq *LikedTrackQuery) Only(ctx context.Context) (*LikedTrack, error) {
	nodes, err := ltq.Limit(2).All(setContextOp(ctx, ltq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{likedtrack.Label}
	default:
		return nil, &NotSingularError{likedtrack.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ltq *LikedTrackQuery) OnlyX(ctx context.Context) *LikedTrack {
	node, err := ltq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LikedTrack ID in the query.
// Returns a *NotSingularError when more than one LikedTrack ID is found.
// Returns a *NotFoundError when no entities are found.
func (ltq *LikedTrackQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ltq.Limit(2).IDs(setContextOp(ctx, ltq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{likedtrack.Label}
	default:
		err = &NotSingularError{likedtrack.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ltq *LikedTrackQuery) OnlyIDX(ctx context.Context) int {
	id, err := ltq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LikedTracks.
func (ltq *LikedTrackQuery) All(ctx context.Context) ([]*LikedTrack, error) {
	ctx = setContextOp(ctx, ltq.ctx, "All")
	if err := ltq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*LikedTrack, *LikedTrackQuery]()
	return withInterceptors[[]*LikedTrack](ctx, ltq, qr, ltq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ltq *LikedTrackQuery) AllX(ctx context.Context) []*LikedTrack {
	nodes, err := ltq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LikedTrack IDs.
func (ltq *LikedTrackQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ltq.ctx.Unique == nil && ltq.path != nil {
		ltq.Unique(true)
	}
	ctx = setContextOp(ctx, ltq.ctx, "IDs")
	if err = ltq.Select(likedtrack.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ltq *LikedTrackQuery) IDsX(ctx context.Context) []int {
	ids, err := ltq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ltq *LikedTrackQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ltq.ctx, "Count")
	if err := ltq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ltq, querierCount[*LikedTrackQuery](), ltq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ltq *LikedTrackQuery) CountX(ctx context.Context) int {
	count, err := ltq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ltq *LikedTrackQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ltq.ctx, "Exist")
	switch _, err := ltq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ltq *LikedTrackQuery) ExistX(ctx context.Context) bool {
	exist, err := ltq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LikedTrackQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ltq *LikedTrackQuery) Clone() *LikedTrackQuery {
	if ltq == nil {
		return nil
	}
	return &LikedTrackQuery{
		config:     ltq.config,
		ctx:        ltq.ctx.Clone(),
		order:      append([]likedtrack.OrderOption{}, ltq.order...),
		inters:     append([]Interceptor{}, ltq.inters...),
		predicates: append([]predicate.LikedTrack{}, ltq.predicates...),
		withTrack:  ltq.withTrack.Clone(),
		// clone intermediate query.
		sql:  ltq.sql.Clone(),
		path: ltq.path,
	}
}

// WithTrack tells the query-builder to eager-load the nodes that are connected to
// the "track" edge. The optional arguments are used to configure the query builder of the edge.
func (ltq *LikedTrackQuery) WithTrack(opts ...func(*TrackQuery)) *LikedTrackQuery {
	query := (&TrackClient{config: ltq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ltq.withTrack = query
	return ltq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DateAdded time.Time `json:"date_added,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LikedTrack.Query().
//		GroupBy(likedtrack.FieldDateAdded).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ltq *LikedTrackQuery) GroupBy(field string, fields ...string) *LikedTrackGroupBy {
	ltq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &LikedTrackGroupBy{build: ltq}
	grbuild.flds = &ltq.ctx.Fields
	grbuild.label = likedtrack.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DateAdded time.Time `json:"date_added,omitempty"`
//	}
//
//	client.LikedTrack.Query().
//		Select(likedtrack.FieldDateAdded).
//		Scan(ctx, &v)
func (ltq *LikedTrackQuery) Select(fields ...string) *LikedTrackSelect {
	ltq.ctx.Fields = append(ltq.ctx.Fields, fields...)
	sbuild := &LikedTrackSelect{LikedTrackQuery: ltq}
	sbuild.label = likedtrack.Label
	sbuild.flds, sbuild.scan = &ltq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a LikedTrackSelect configured with the given aggregations.
func (ltq *LikedTrackQuery) Aggregate(fns ...AggregateFunc) *LikedTrackSelect {
	return ltq.Select().Aggregate(fns...)
}

func (ltq *LikedTrackQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ltq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ltq); err != nil {
				return err
			}
		}
	}
	for _, f := range ltq.ctx.Fields {
		if !likedtrack.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ltq.path != nil {
		prev, err := ltq.path(ctx)
		if err != nil {
			return err
		}
		ltq.sql = prev
	}
	return nil
}

func (ltq *LikedTrackQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*LikedTrack, error) {
	var (
		nodes       = []*LikedTrack{}
		withFKs     = ltq.withFKs
		_spec       = ltq.querySpec()
		loadedTypes = [1]bool{
			ltq.withTrack != nil,
		}
	)
	if ltq.withTrack != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, likedtrack.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*LikedTrack).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &LikedTrack{config: ltq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ltq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ltq.withTrack; query != nil {
		if err := ltq.loadTrack(ctx, query, nodes, nil,
			func(n *LikedTrack, e *Track) { n.Edges.Track = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ltq *LikedTrackQuery) loadTrack(ctx context.Context, query *TrackQuery, nodes []*LikedTrack, init func(*LikedTrack), assign func(*LikedTrack, *Track)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*LikedTrack)
	for i := range nodes {
		if nodes[i].track_liked == nil {
			continue
		}
		fk := *nodes[i].track_liked
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(track.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "track_liked" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ltq *LikedTrackQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ltq.querySpec()
	_spec.Node.Columns = ltq.ctx.Fields
	if len(ltq.ctx.Fields) > 0 {
		_spec.Unique = ltq.ctx.Unique != nil && *ltq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ltq.driver, _spec)
}

func (ltq *LikedTrackQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(likedtrack.Table, likedtrack.Columns, sqlgraph.NewFieldSpec(likedtrack.FieldID, field.TypeInt))
	_spec.From = ltq.sql
	if unique := ltq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ltq.path != nil {
		_spec.Unique = true
	}
	if fields := ltq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, likedtrack.FieldID)
		for i := range fields {
			if fields[i] != likedtrack.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ltq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ltq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ltq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ltq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ltq *LikedTrackQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ltq.driver.Dialect())
	t1 := builder.Table(likedtrack.Table)
	columns := ltq.ctx.Fields
	if len(columns) == 0 {
		columns = likedtrack.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ltq.sql != nil {
		selector = ltq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ltq.ctx.Unique != nil && *ltq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ltq.predicates {
		p(selector)
	}
	for _, p := range ltq.order {
		p(selector)
	}
	if offset := ltq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ltq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LikedTrackGroupBy is the group-by builder for LikedTrack entities.
type LikedTrackGroupBy struct {
	selector
	build *LikedTrackQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ltgb *LikedTrackGroupBy) Aggregate(fns ...AggregateFunc) *LikedTrackGroupBy {
	ltgb.fns = append(ltgb.fns, fns...)
	return ltgb
}

// Scan applies the selector query and scans the result into the given value.
func (ltgb *LikedTrackGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ltgb.build.ctx, "GroupBy")
	if err := ltgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikedTrackQuery, *LikedTrackGroupBy](ctx, ltgb.build, ltgb, ltgb.build.inters, v)
}

func (ltgb *LikedTrackGroupBy) sqlScan(ctx context.Context, root *LikedTrackQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ltgb.fns))
	for _, fn := range ltgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ltgb.flds)+len(ltgb.fns))
		for _, f := range *ltgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ltgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ltgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// LikedTrackSelect is the builder for selecting fields of LikedTrack entities.
type LikedTrackSelect struct {
	*LikedTrackQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (lts *LikedTrackSelect) Aggregate(fns ...AggregateFunc) *LikedTrackSelect {
	lts.fns = append(lts.fns, fns...)
	return lts
}

// Scan applies the selector query and scans the result into the given value.
func (lts *LikedTrackSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, lts.ctx, "Select")
	if err := lts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*LikedTrackQuery, *LikedTrackSelect](ctx, lts.LikedTrackQuery, lts, lts.inters, v)
}

func (lts *LikedTrackSelect) sqlScan(ctx context.Context, root *LikedTrackQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(lts.fns))
	for _, fn := range lts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*lts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
