// Code generated by ent, DO NOT EDIT.

package ent

import (
	"orkester/ent/likedtrack"
	"orkester/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	likedtrackFields := schema.LikedTrack{}.Fields()
	_ = likedtrackFields
	// likedtrackDescDateAdded is the schema descriptor for date_added field.
	likedtrackDescDateAdded := likedtrackFields[0].Descriptor()
	// likedtrack.DefaultDateAdded holds the default value on creation for the date_added field.
	likedtrack.DefaultDateAdded = likedtrackDescDateAdded.Default.(func() time.Time)
}
